version: "3.8"
services:

  # Bee node
  beedev:
    hostname: beedev
    image: ethersphere/bee:1.4.0
    restart: unless-stopped
    environment:
      - BEE_DEBUG_API_ENABLE=true
      - BEE_FULL_NODE=true
      - BEE_PASSWORD=swarm
      - BEE_SWAP_ENDPOINT=https://goerli.infura.io/v3/31e9da197fb147fcac02d6a8e4bce616
    networks:
      - bee-net
    ports:
      - 1633:1633 # gateway api
      - 1634:1634 # p2p
      - 1635:1635 # debug api
    volumes:
      - beedev:/home/bee/.bee
    command: start
    
  # FairOS-dfs
  dfsserverdev:
    image: etherna/fairos-dfs:master
    volumes:
      - dfs-server:/go/fairOS-dfs/dist/data
    depends_on:
      - beedev
    restart: unless-stopped
    networks:
      - bee-net
    ports:
      - 9090:9090
    entrypoint: [ "/go/fairOS-dfs/dist/dfs", "server", "--beeHost", "beedev", "--beePort", "1633", "--dataDir", "/go/fairOS-dfs/dist/data" ]
    
  # IntegrationTest
  beenet.integrationtest:
    image: ${DOCKER_REGISTRY-}beenetintegrationtest
    build:
      context: .
      dockerfile: test/BeeNet.IntegrationTest/Dockerfile

networks:
  bee-net:
      
volumes:
  beedev:
  dfs-server: