// Copyright 2021-present Etherna SA
// This file is part of Bee.Net.
// 
// Bee.Net is free software: you can redistribute it and/or modify it under the terms of the
// GNU Lesser General Public License as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any later version.
// 
// Bee.Net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License along with Bee.Net.
// If not, see <https://www.gnu.org/licenses/>.

using Etherna.BeeNet.Models;
using System;

namespace Etherna.BeeNet.Hashing.Pipeline
{
    public sealed class HasherPipelineFeedArgs
    {
        // Fields.
        private readonly byte[] _data;
        private readonly byte[]? _span;
        
        // Constructor.
        public HasherPipelineFeedArgs(
            byte[] data,
            byte[]? span = null,
            long numberId = 0)
        {
            ArgumentNullException.ThrowIfNull(data, nameof(data));
            
            if (span is not null)
            {
                if (data.Length < SwarmChunk.SpanSize)
                    throw new InvalidOperationException("Data must contain also span, if present");
                if (span.Length != SwarmChunk.SpanSize)
                    throw new ArgumentOutOfRangeException(nameof(span), $"Span must have length of {SwarmChunk.SpanSize}");
            }
            
            _data = data;
            _span = span;
            NumberId = numberId;
        }
        
        // Properties.
        /// <summary>
        /// Data can include the span too, but it may be encrypted if the pipeline is encrypted
        /// </summary>
        public ReadOnlyMemory<byte> Data => _data;
        
        /// <summary>
        /// Hash generated by BMT
        /// </summary>
        public SwarmHash? Hash { get; set; }

        /// <summary>
        /// Always unecrypted span uint64
        /// </summary>
        public ReadOnlyMemory<byte> Span => _span;
        
        /// <summary>
        /// Ordered Id, from 0 to n with the last chunk
        /// </summary>
        public long NumberId { get; }
    }
}