name: Integration Test
 
on:
  push:
    branches:
    - main
    - release/*
    - dev

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      #BeeNet_IT_NodeEndPoint: "http://89.145.161.170/"
      BeeNet_IT_NodeEndPoint: "http://127.0.0.1/"
      BeeNet_IT_NodeVersion: "1.6.1"

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0

    - name: Install BeeFactory
      run: npm install -g @ethersphere/bee-factory
      

    - name: Star Bee Nodes
      run: bee-factory start --detach "${{env.BeeNet_IT_NodeVersion}}" 
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore BeeNet.sln

    - name: Build
      run: dotnet build BeeNet.sln --no-restore 

    - name: Test
      run: dotnet test BeeNet.sln --no-build --verbosity normal
