name: Integration Test

on:
  push:
    branches: [ "BNET-11-IntegrationTest" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BeeNet_IT_NodeEndPoint: "http://89.145.161.170/"

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
